### ISSUE TITLE
Less/More Tables should also have totals

### ISSUE THREAD

**Issue by PsychicMuffin** [PsychicMuffin/PathOfDamage#18]
Although the totals for those fields need to be calculated differently since they are multiplicative. This will cause some decent refactoring throughout the code since I do checks for if totals exist, which I wouldn't need to do anymore, and I calculate all totals the same, which would have to change.

**Comment by ficocelliguy** [comment]
In the layoutReformat branch I have added simple totals to those sections, but I didn't touch the math. If you have a good fix I can just resolve to that.

**Comment by PsychicMuffin** [comment]
you can just enter that and I'll do the refactoring, and leave this open until I finish it.

**Comment by ficocelliguy** [comment]
Right now we get values like 
Total: 14.000000000000014%

We need to round after your calcs I think
