### ISSUE TITLE
All placeholder text should include "name" somewhere

### ISSUE THREAD

**Issue by PsychicMuffin** [PsychicMuffin/PathOfDamage#19]
It's very possible for a user to quickly start entering data and not realize why it's not functioning properly

**Comment by ficocelliguy** [comment]
I added table headers in the layoutReformat branch, which helps, but I agree that this is a good idea

**Comment by PsychicMuffin** [comment]
Labeled as a bug since now that there are table headers, the placeholder text for every table should probably just be "Name", and we can remove the placeholderText variable
