### ISSUE TITLE
Showing totals

### ISSUE THREAD

**Issue by PsychicMuffin** [PsychicMuffin/PathOfDamage#54]
Right now it is extremely unintuitive what the total is actually showing. We should probably show totals for each element that has a value, possibly iconify them and only show the element name via tooltip.

**Comment by ficocelliguy** [comment]
Related: The label "total" is kind of misleading in 'more' sections.
Total implies the sum of parts, but "more" tables don't really do that. The label should probably be "More:" instead or something.

This was previously tracked in #42 but I'm combining them here.

**Comment by PsychicMuffin** [comment]
13x13 Icons have proven difficult to find, so we can use P: F: C: L: C: with associated colors until we find/make some
