### ISSUE TITLE
Mind over Mater is not accounted for anywhere

### ISSUE THREAD

**Issue by PsychicMuffin** [PsychicMuffin/PathOfDamage#57]
Not entirely sure if we can correctly account for it, because it does have mana requrements, but we can assume the user has sufficient mana if they have MoM "enabled" somehow

**Comment by ficocelliguy** [comment]
Per discussion: It would be nice to enter total damage taken from mana from Cloak of Defiance, ascendancies, MoM, etc. This would probably be a new table in the damage shifts section (which should probably be renamed, though the wiki calls it 'damage taken as' and only uses 'shift' informally). We would need to ask for unreserved mana; For small hits the effect would be a less multiplier, but if you don't have enough mana to absorb 30% of a large hit, it is simply a flat decrease.
